name: vehicle_rental_frontendui
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.11
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

#product
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  tab_container: ^3.5.3
  animated_toggle_switch: ^0.8.3


  #image
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logos/
    - assets/banners/
    - assets/categories/
    - assets/icons/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
    - family: coolvetica
      fonts:
        - asset: fonts/coolvetica_regular.otf
          weight: 800
        - asset: fonts/coolvetica_regular_italic.otf
          weight: 600
